<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Be.Windows.Forms.HexBox" Version="1.6.1" />
    <PackageReference Include="ICSharpCode.TextEditorEx" Version="1.3.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4022.49" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Data.SQLite" Version="1.0.119" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.7" />
  </ItemGroup>

</Project>